version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: hospital_postgres
    environment:
      POSTGRES_DB: hospital_db
      POSTGRES_USER: hospital_user
      POSTGRES_PASSWORD: hospital_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hospital_user -d hospital_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: hospital_redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: hospital_backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py seed_data &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-hospital-management-system-super-secret-key-2026
      - DEBUG=True
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=hospital_db
      - DB_USER=hospital_user
      - DB_PASSWORD=hospital_pass
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  celery:
    build: ./backend
    container_name: hospital_celery
    command: celery -A config worker -l info
    volumes:
      - ./backend:/app
    environment:
      - SECRET_KEY=django-insecure-hospital-management-system-super-secret-key-2026
      - DEBUG=True
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=hospital_db
      - DB_USER=hospital_user
      - DB_PASSWORD=hospital_pass
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis

  frontend:
    build: ./frontend
    container_name: hospital_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend

volumes:
  postgres_data:
